# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='tel\xe9fono')),
                ('celular', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('celular_2', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.CharField(blank=True, max_length=100, null=True)),
                ('longitud', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Direcci\xf3n')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
