# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 04:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cojin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('tamanio', models.IntegerField(default=0, verbose_name='tama\xf1o')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='descripci\xf3n')),
                ('precio_yarda', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='precio por yarda')),
                ('modificado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cojin',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='cojines.Material'),
        ),
    ]
