# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 00:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20170727_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='bordado',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='bordado',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True),
        ),
    ]
